// toast('Start');
// sleep(1000);
// text('卖出').click();
// sleep(1000);
// toast('Done');
// text('确认卖出').click();
// TransformStream('Start');
// SVGPathSegClosePath(1000);
toast('start');
sleep(1000);
back();